server:
  port: 8085

spring:
  application:
    name: curriculum-service
  cloud:
    consul:
      host: 13.82.103.66
      port: 8500
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  devtools:
    restart:
      enabled: true
  datasource:
    driver-class: com.microsoft.sqlserver.jdbc.SQLserverDriver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    jpa:
      show-sql: true
      generate-ddl: true
      hibernate:
        ddl-auto: update

---

server:
  port: 8085
spring:
  application:
    name: curriculum-service-dev
  cloud:
    consul:
      host: localhost
      port: 8500
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class: com.microsoft.sqlserver.jdbc.SQLserverDriver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    jpa:
      show-sql: true
      generate-ddl: true
      hibernate:
        ddl-auto: update

